In [1]:
import numpy as np
import pandas as pd


In [13]:
df = pd.read_csv('/content/sample_data/customer.csv')
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [14]:
df = df.iloc[:,2:]
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [16]:
x_train

review education
38     Good    School
14     Poor        PG
21  Average        PG
40     Good    School
33     Good        PG
27     Poor        PG
7      Poor    School
49     Good        UG
10     Good        UG
5   Average    School
25     Good    School
18     Good    School
48     Good        UG
15     Poor        UG
45     Poor        PG
28     Poor    School
4   Average        UG
13  Average    School
20  Average    School
39     Poor        PG
0   Average    School
8   Average        UG
1      Poor        UG
26     Poor        PG
23     Good    School
36     Good        UG
9      Good        UG
24  Average        PG
17     Poor        UG
34  Average    School
41     Good        PG
19     Poor        PG
12     Poor    School
16     Poor        UG
29  Average        UG
32  Average        UG
44  Average        UG
6      Good    School
37  Average        PG
11     Good        UG

In [17]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'],['School','UG','PG']])
oe.fit(x_train)


OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [18]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

x_train

array([[2., 0.],
       [0., 2.],
       [1., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [2., 1.],
       [1., 2.],
       [0., 1.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [2., 0.],
       [1., 2.],
       [2., 1.]])

In [19]:
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [21]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)
y_train,y_test

(array([0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1]),
 array([1, 1, 0, 1, 0, 1, 0, 1, 0, 0]))

In [22]:
le.classes_

array(['No', 'Yes'], dtype=object)